# # #QUESTION_1
# def sum_squares_abs_diff_squares(a:int, b:int) -> tuple:
#     '''Return the sum of squares and the absolute difference of squares.

#     Args:
#         a, b : int - input numbers

#     Returns:
#         tuple - tuple with sum of squares and absolute difference of squares.

#     '''
#     sum_sq1 = a**2
#     sum_sq2 = b**2
#     add_sq = sum_sq1 + sum_sq2
#     abs_diff = abs(sum_sq1 - sum_sq2)
#     return (add_sq,abs_diff)


# print(sum_squares_abs_diff_squares(2, 3))
# print(sum_squares_abs_diff_squares(2, 6))
# print(sum_squares_abs_diff_squares(5, 2))
# print(sum_squares_abs_diff_squares(6, 8))

# # QUESTION_2
# def is_odd_length_palindrome(s: str) -> bool:
#     '''Check if a string is a palindrome with odd length.

#     Args:
#         s : str - input string

#     Returns:
#         bool - True if s is a palindrome with odd length, False otherwise.
#     '''
#     #bool 
#     if len(s) % 2 == 0:
#         return False 
#     rev_s = s[::-1]
#     return s == rev_s

# print(is_odd_length_palindrome("hello"))
# print(is_odd_length_palindrome("nun"))
# print(is_odd_length_palindrome("noon")




    




    